# code to learn about a function called Range
user = int(input("enter a number which is the end point of our counting table"))
HEY = list(range(1, user, 1))
print(HEY)
print("Now we will print the same seqence, but for even numbers")
OM = list(range(2, user, 2))
print(OM)
print("Now we will do the same, but for odd numbers")
SHANTIOM = list(range(1, user, 2))
print(SHANTIOM)